-- DROP DATABASE IF EXISTS exampledb;
-- CREATE DATABASE exampledb;
-- CREATE DATABASE testdb;

DROP DATABASE IF EXISTS deardoctor_db;
CREATE DATABASE deardoctor_db;

CREATE TABLE symptom (
	id INTEGER AUTO_INCREMENT NOT NULL,
	symptom VARCHAR(255) NULL,
	severity INTEGER NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	heal_id INTEGER,
	PRIMARY KEY(id)
	-- FOREIGN KEY(heal_id) REFERENCES patientInfo(heal_id)
);

CREATE TABLE food (
	id INTEGER AUTO_INCREMENT NOT NULL,
	food TEXT(255) NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	heal_id INTEGER,
	PRIMARY KEY(id)
	-- FOREIGN KEY(heal_id) REFERENCES patientInfo(heal_id)
);

	CREATE TABLE drink (
	id INTEGER AUTO_INCREMENT NOT NULL,
	drink TEXT(255) NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	heal_id INTEGER,
	PRIMARY KEY(id)
	-- FOREIGN KEY(heal_id) REFERENCES patientInfo(heal_id)
);